; ========================================================================================================================
; * Created by: Holtek Touch MCU Workshop, Version 3.5.1.0
; USER_PROGRAM.inc
; 12:15:00 AM Sunday, November 04, 2018
; ========================================================================================================================
#include "..\TKS_GLOBE_VARIES.inc" 
#include "..\BS67F350_LIBV413\BS67F350_LIBV413.aex" 
#include "..\MAIN_PROGRAM_V104\MAIN_PROGRAM_V104.aex" 
