; ========================================================================================================================
; * Created by: Holtek Touch MCU Workshop, Version 3.5.1.0
; MAIN_PROGRAM_V104.inc
; 12:15:00 AM Sunday, November 04, 2018
; ========================================================================================================================
#include "..\TKS_GLOBE_VARIES.inc" 
#include "MAIN_PROGRAM_20170905.MCU" 
#include "..\BS67F350_LIBV413\BS67F350_LIBV413.aex" 
#define                                
#define EXTEND_FUNCTION_1A_INITIAL     _BS67F350_LIBV413_INITIAL
#define EXTEND_FUNCTION_1A             _BS67F350_LIBV413
#include "..\USER_PROGRAM\USER_PROGRAM.aex" 
#define                                
#define EXTEND_FUNCTION_1B_INITIAL     _USER_PROGRAM_INITIAL
#define EXTEND_FUNCTION_1B             _USER_PROGRAM
